import { NextRequest, NextResponse } from "next/server";

const CHIP_SECRET_KEY = process.env.CHIP_SECRET_KEY;
const CHIP_BRAND_ID = process.env.CHIP_BRAND_ID;

export async function POST(req: NextRequest) {
    try {
        const {
            amount,
            client_name,
            client_email,
            client_phone,
            booking_date,
            adults,
            kids,
            seniors = 0,
            focKids = 0,
            table_size,
            language
        } = await req.json();

        if (!CHIP_SECRET_KEY || !CHIP_BRAND_ID) {
            console.error("Missing Chip API Keys");
            return NextResponse.json(
                { error: "Payment gateway configuration error." },
                { status: 500 }
            );
        }

        // Prepare exactly what we need for Chip in Asia "Purchases" creation
        const payload = {
            success_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/success`,
            failure_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/cancel`,
            cancel_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/cancel`,
            creator_agent: "RSVP Booking System",
            reference: `BKA-${Date.now()}`,
            send_receipt: true,
            client: {
                email: client_email,
                phone: client_phone,
                full_name: client_name,
                // Tracking data embedded in personal_code for webhook parsing
                personal_code: `Date:${booking_date}|A:${adults}|K:${kids}|S:${seniors}|F:${focKids}|T:${table_size}`,
            },
            purchase: {
                timezone: "Asia/Kuala_Lumpur",
                currency: "MYR",
                products: [
                    {
                        name: `${language === "ms" ? "Tempahan Meja" : "Table Reservation"} (${booking_date}) - ${adults} Dewasa, ${kids} Kanak-kanak, ${seniors} Warga Emas/OKU, ${focKids} FOC Kids`,
                        price: Math.round(amount * 100), // Chip expects amount in cents
                        quantity: 1,
                        tax_percent: 6, // Automatically adds 6% SST
                    }
                ],
            },
            brand_id: CHIP_BRAND_ID,
        };

        const response = await fetch("https://gate.chip-in.asia/api/v1/purchases/", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${CHIP_SECRET_KEY}`,
            },
            body: JSON.stringify(payload),
        });

        const data = await response.json();

        if (!response.ok) {
            console.error("Chip API Error:", data);
            return NextResponse.json(
                { error: data.message || "Failed to initialize payment." },
                { status: response.status }
            );
        }

        // Return the specific checkout URL parameter generated by Chip
        const checkoutUrl = data.checkout_url;

        // We no longer reserve the table pre-payment to avoid "Unpaid" sheet clutter.
        // It will be exclusively handled by the successful Webhook callback.

        return NextResponse.json({ checkoutUrl: checkoutUrl });

    } catch (error) {
        console.error("Internal Server Error:", error);
        return NextResponse.json(
            { error: "Internal Server Error" },
            { status: 500 }
        );
    }
}
