import { NextRequest, NextResponse } from "next/server";

const CHIP_SECRET_KEY = process.env.CHIP_SECRET_KEY;
const CHIP_BRAND_ID = process.env.CHIP_BRAND_ID;

export async function POST(req: NextRequest) {
    try {
        const {
            amount,
            client_name,
            client_email,
            client_phone,
            booking_date,
            adults,
            kids,
            seniors = 0,
            focKids = 0,
            table_size,
            language
        } = await req.json();

        if (!CHIP_SECRET_KEY || !CHIP_BRAND_ID) {
            console.error("Missing Chip API Keys");
            return NextResponse.json(
                { error: "Payment gateway configuration error." },
                { status: 500 }
            );
        }

        // Prepare exactly what we need for Chip in Asia "Purchases" creation
        const payload = {
            success_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/success`,
            failure_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/cancel`,
            cancel_redirect: `${process.env.NEXT_PUBLIC_URL || req.headers.get("origin")}/cancel`,
            creator_agent: "RSVP Booking System",
            reference: `BKA-${Date.now()}`,
            send_receipt: true,
            client: {
                email: client_email,
                phone: client_phone,
                full_name: client_name,
                // Tracking data embedded in personal_code for webhook parsing
                // Compact format: DDMMYY|Adults|Kids|Seniors|FocKids (stays well under 32 chars)
                personal_code: (() => {
                    const d = new Date(booking_date)
                    const dd = String(d.getDate()).padStart(2, '0')
                    const mm = String(d.getMonth() + 1).padStart(2, '0')
                    const yy = String(d.getFullYear()).slice(-2)
                    return `${dd}${mm}${yy}|${adults}|${kids}|${seniors}|${focKids}`
                })(),
            },
            purchase: {
                timezone: "Asia/Kuala_Lumpur",
                currency: "MYR",
                products: [
                    {
                        name: `${language === "ms" ? "Tempahan Meja" : "Table Reservation"} (${booking_date}) - ${adults} Dewasa, ${kids} Kanak-kanak, ${seniors} Warga Emas/OKU, ${focKids} FOC Kids`,
                        price: Math.round(amount * 100), // Chip expects amount in cents
                        quantity: 1,
                        tax_percent: 6, // Automatically adds 6% SST
                    }
                ],
            },
            brand_id: CHIP_BRAND_ID,
        };

        const response = await fetch("https://gate.chip-in.asia/api/v1/purchases/", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${CHIP_SECRET_KEY}`,
            },
            body: JSON.stringify(payload),
        });

        const data = await response.json();

        if (!response.ok) {
            console.error("Chip API Error:", data);
            return NextResponse.json(
                { error: data.message || "Failed to initialize payment." },
                { status: response.status }
            );
        }

        // Return the specific checkout URL parameter generated by Chip
        const checkoutUrl = data.checkout_url;

        // NEW: Pre-payment Seat Locking
        // Before redirecting the user to Chip, we MUST reserve a seat in the Google Sheet.
        // This prevents the race condition where multiple users pay for the last seat.
        const scriptUrl = process.env.GOOGLE_SCRIPT_URL;
        if (scriptUrl) {
            const bookingPayload = {
                action: "createBooking",
                name: client_name,
                date: booking_date,
                adults: parseInt(adults, 10),
                kids: parseInt(kids, 10),
                seniors: parseInt(seniors, 10) || 0,
                focKids: parseInt(focKids, 10) || 0,
                phone: client_phone,
                email: client_email,
                totalAmount: amount,
                reference: payload.reference
            };

            try {
                const sheetRes = await fetch(scriptUrl, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(bookingPayload)
                });

                const sheetData = await sheetRes.json();
                if (!sheetData.success) {
                    // Google Sheet says it's FULL or failed to allocate. 
                    // Stop checkout immediately.
                    console.error("Overbooking prevented. Seat allocation failed:", sheetData.message);
                    return NextResponse.json(
                        { error: "We are sorry, but the remaining tables were just booked by someone else. Please try another date." },
                        { status: 409 }
                    );
                }
            } catch (err) {
                console.error("Failed to allocate seat pre-payment:", err);
                // We proceed with the checkout if Google Script timeouts, falling back to Webhook Safety Net.
            }
        }

        return NextResponse.json({ checkoutUrl: checkoutUrl });

    } catch (error) {
        console.error("Internal Server Error:", error);
        return NextResponse.json(
            { error: "Internal Server Error" },
            { status: 500 }
        );
    }
}
